export const RESET_STOPWATCH = 'RESET_STOPWATCH'
export const START_STOPWATCH = 'START_STOPWATCH'
    export const STOP_STOPWATCH = 'STOP_STOPWATCH'
    export const ACTIVE_STOPWATCH = 'ACTIVE_STOPWATCH'
